---
- name: Install and configure webapp with nginx and gunicorn on Debian host
  hosts: all
  gather_facts: no
  vars:
    # Use python3 instead python2 because Ubuntu Trusty with python 2.7.6 has TLS issue due obtaining nginx repo key
    ansible_python_interpreter: "/usr/bin/env python3"

  pre_tasks:
    - name: Install python for Ansible
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
#      raw: test -e /usr/bin/python2 -o -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
#      when: ansible_os_family == 'Debian'
      changed_when: false

    - action: setup

    - name: Install git
      become: true
      when: ansible_os_family == 'Debian'
      apt:
        name: git
        update_cache: yes
        cache_valid_time: 3600
        state: present

  roles:
    - webapp
